### ISSUE TITLE
Version ^2.6 doesn't support phpunit:^6.0

### ISSUE THREAD

**Issue by icanhazstring** [zendframework/zend-test#57]
I would file a pull request but the tag at `2.6.1` is not originated from a certain branch.
Would be nice if you can add 2.6.2 with support for `phpunit/phpunit:^6.0`.

**Why I need this**
Currently I am in the middle of migrating from zendframework:2.5 to 2.7 (getServiceLocator() deprecation and middleware in mvc). This is the only thing I want to do. The problem is, I can't file any Controller tests since I am using `phpunit/phpunit:^6.0` and `zendframework/zend-test:^2.6` is locked with phpunit/phpunit:^4.0 || ^5.0`.

**Comment by weierophinney** [comment]
This is a non-trivial change, unfortunately, as PHPUnit 6 makes changes that are backwards incompatible, including:

- All classes use namespaces exclusively. This alone means changes in every single class, all of which would be backwards incompatible with PHPUnit 4, as well as PHPUnit 5 versions prior to 5.7.
- Methods such as `setExpectedException()` are no longer available in PHPUnit 6 and up, while, simultaneously, the replacement `expectException*()` methods are not available in version 4.

While I understand your frustration, upgrading to allow PHPUnit 6 and up is simply not possible within the v2 series, due to these incompatibilities. You will need to use PHPUnit 5 if you want to provide controller tests compatible with the 2.6 series.

**Comment by icanhazstring** [comment]
Wo such an old issue :D
Now that you mention it you can't use PHPUnit 5 and 6 contraint since these are totally incompatible.

Thanks anyway for the response anyway :)
