### ISSUE TITLE
Value "phpunit" in route parameters

### ISSUE THREAD

**Issue by Scyt8l3** [zendframework/zend-test#61]
Hi,

I'd like to test a route with a parameter that has value "phpunit" but i've an 404 route not found error. If I try with an other value it's work. Is it something to configure or do?

Thanks in advance.

ps: Sorry for any spelling fault, english is not my mother tongue.

**Comment by michalbundyra** [comment]
@Scyt8l3 Can you provide unit test with it? I don't think that there is any restriction about param values.

**Comment by Scyt8l3** [comment]
@webimpress 

Sorry for my late response, I've redo some test. And I'm thinking that I've found.

The problem is in \Zend\Http\PhpEnvironment\Request (line 543):
"phpunit" is the base name from executable and It take a strpos on my request uri (ex.: '/auth/password/reset/phpunit@domain.email/mNilrJMd7o9EG0wvN7tYOJffCiLhFvfyzzttwvS8F7Y') and thus doesn't take the begining of my route.

**Comment by michalbundyra** [comment]
@Scyt8l3 I checked it and I can confirm there is an issue. Please see my solution in #66. Would you be able to test that branch with your application please?

I clear all global arrays in tests setUp. For me it works, because we shouldn't build there any request from globals, but maybe I'm missing something and there is another failing test case.
